### ISSUE TITLE
Issues with documentation

### ISSUE THREAD

**Issue by amartyabose** [i-pi/i-pi#128]
Hi,

I have been using i-pi mostly for routine PIMD for some time now.  I have just started getting into the more advanced features.  I realized that some of the documentation is either inconsistent or may be I am not interpreting it correctly.  For instance, on page 25 of the pdf manual, the explanation of the variable "atom_x_path" says that it can also take the bead number for a particular atom.  However, I checked the code, and it has no provision for a bead number in there.  If only a few particular beads of an atom are required, like in the case of an end-to-end distribution, the "atom_x" variable would probably be more apt.

If someone would guide me with the basic conventions of the project, I would love to help with the changes required in this and other things.

Thanks for the wonderful code!

Amartya

**Comment by mahrossi** [comment]
Dear Amartya,

Thanks for the message. We are aware that the documentation could be improved and we are very very happy to get on board anyone that wants to help. If you have time, a few of us could have quick zoom session with you so you can ask the main questions you have regarding the package, and we can tell you how to update the documentation. In general, you can fork the repository, make a new branch where you do your modifications and then open a pull request to merge that back into this main repository. We review the pull request, so we can also discuss practical cases on how to best modify the code there. 

Otherwise, basic formatting and documenting rules are stated on the initial webpage here (in the README). 

Sorry for the delayed answer and hope to hear from you soon!

Mariana

**Comment by amartyabose** [comment]
Dear Mariana,

Thank you for the reply!  I have forked the repository, and will start seeing what modifications I can do by myself.  I am free most of the week to zoom.  If you are free, please let me know, I would love to know what other features are on the priority list for the package currently.

Thanks,
Amartya

**Comment by fidanyan** [comment]
Hi Amartya, 

Sorry for a long silence! I looked into the issue with `atom_x` and `atom_x_path`: indeed, there is a mistake in documentation.
The main thing is that the documentation in i-PI is compiled in semi-automated way from the python source files. Many structures in python have `"help"` fields, which are then collected into a manual.
If you are interested in contributing to the code, I can introduce you the idea via Zoom/Skype.

Best regards,
Karen

**Comment by amartyabose** [comment]
Dear Karen,

I am so sorry!  I thought I had replied to you.  I was really caught up these past few weeks.  Yes, I am interested in contributing to the code.  I was looking through the code base and had a few questions about how the force gets updated.  I believe there is some automatic way by which on updating the positions, the force object bound to that position updates it's values.  This is also reflected in the documentation where it states for instance that for the Displaced Path Integral method "each path opening operation costs as much as a PIMD step."  If I am reading the code correctly it is using the free energy perturbation method (eqn 4 of [1]).  In which case, the force need not be computed, and energy computations can be done much faster than the force computations required for a full PIMD step.  Please let me know if you can explain me this part of the code so that we can make it more efficient.

Sorry for the late reply!

Best,
Amartya

1. Lin, L., Morrone, J. A., Car, R., & Parrinello, M. (2010). Displaced Path Integral Formulation for the Momentum Distribution of Quantum Particles. Physical Review Letters, 105(11), 110602. https://doi.org/10.1103/PhysRevLett.105.110602

**Comment by ceriottm** [comment]
Depends on the method you use, but 99% of the time computing the force adds
small overhead over getting just the energy. That's the whole point of
doing MD vs MC.

**Comment by fidanyan** [comment]
Hi Amartya,

If I understand your question correctly, you ask about the dependence mechanism in i-PI. It is described in the section 1.3.1 of the manual. You are right: forces are a "depend" object, which tracks changes in its dependencies and requires recalculation if the dependencies have been changed.
Many DFT codes don't allow to decide on each step whether this step should return forces or just the energy. And i-PI by design is agnostic about the internal features of client codes and treats all of them equally. Therefore, a call to a calculator code always requests forces to be returned (ipi/interfaces/sockets.py: Driver.getforce()).

Best,
Karen

**Comment by amartyabose** [comment]
Ok! Thanks!
