### ISSUE TITLE
How to embody isotope effect in i-PI?

### ISSUE THREAD

**Issue by 1597446909** [i-pi/i-pi#205]
Hello,I have a question that if I want to simulation isotope He-3 and He-4,how to set the parameters in the 'isotope_tdfep'.I want to creat a system consisted of some He-3 atoms and some He-4 atoms.However,I watch the manual and then find the 'isotope_tdfep' have 2 two parameters,and the second parameter 'atom'  can be a label or a int index.but if 'atom' = label such as 'He' and I set the scaled mass α,which means I'll replace all He-4 atoms with He-3 atoms;if 'atom'=index such as  '1',which means I only replace a He-4 atom with a He-3 atom,and the rest of system atoms still is He-4 atoms.so I want to consult,how to make the systems consisted of a part of He-3 atoms and a part of He-4 atoms.
Thanks you.Look forward to your reply

**Comment by ceriottm** [comment]
Hi can I ask you to ask the question on the forum https://groups.google.com/g/ipi-users ? 
We prefer to keep github for bugs / development, and have all user questions there. 
Thanks!

**Comment by 1597446909** [comment]
Hello ！I jion the googlegroups but I cant the question by gmai.It show blocked.Could you tell me how to use the tag<masses>.I want to initialize some atoms which have same element in different mass.For example,I want to initialize five He-3 atoms and five He-4 atoms.Can I give code like this？:<masses mode='manual'>[3,3,3,3,3,4,4,4,4,4]</masses>Or:<masses mode='manual' index=[0,1,2,3,4]>3</masses><masses mode='manual' index=[5,6,7,8,9]>4</masses>Or some else.Thanks you.Looking forward to your reply and wishing you have a good time.-------- 原始邮件 --------发件人： Michele Ceriotti ***@***.***>日期： 2022年4月10日周日 下午4:34收件人： i-pi/i-pi ***@***.***>抄送： 1597446909 ***@***.***>, Author ***@***.***>主    题： Re: [i-pi/i-pi] How to embody isotope effect in i-PI? (Issue #205)
Hi can I ask you to ask the question on the forum https://groups.google.com/g/ipi-users ?
We prefer to keep github for bugs / development, and have all user questions there.
Thanks!

**Comment by ceriottm** [comment]
Weird. Did you try input your question from the web interface? Are you behind the Great Chinese Firewall? Did they start blocking google groups? Anyway, given that the only thing i-PI uses the atom names for is to give them masses, I would use He for He4, and H for He3, and then set the ranges for the alpha so that it makes the masses equal to He3. Alternatively you can also set the masses manually, but you have to be careful to make sure everything functions as it should - add a few print statements here and there to make sure the mass is what it should be.
