### ISSUE TITLE
i-PI can now be used with AMS

### ISSUE THREAD

**Issue by mhellstr** [i-pi/i-pi#253]
Dear i-PI developers,

The Amsterdam Modeling Suite and all its compute methods (DFT, DFTB, ReaxFF, force fields, ML potentials, ...), can now be coupled to i-PI with minimal overhead.

I'd greatly appreciate if you could mention AMS as one of the supported codes on https://ipi-code.org/

There's an example for TRPMD with the UFF force field on https://www.scm.com/doc/plams/examples/i-PI-AMS.html

**Comment by mahrossi** [comment]
Dear Matti -- GREAT NEWS! I will add it to the webpage ASAP. Would you like to also include an example with AMS input files in the i-PI repo? We normally have those and we are re-structuring the examples folder to highlight code examples. See https://github.com/i-pi/i-pi/pull/245 -- we are more than happy if you can contribute with that example.

**Comment by mhellstr** [comment]
Great, thanks! Yes, feel free to include it as an example. Note that there are four files needed (run-ase.py, firstframe.xyz, input.xml, and run-server.sh). If in the example you could also link to "our" version of the example that would be good, as it's easier for us to update it in case it would be needed.

**Comment by mahrossi** [comment]
Ok, we will add it with that PR! Our webpage is updated now.

**Comment by ceriottm** [comment]
Was this included in the end? I'm trying to go through the issues and close those that are solved.

**Comment by mhellstr** [comment]
I don't think this has been included. If the responsibility is mine to do anything with this, please let me know.

**Comment by mahrossi** [comment]
Hi @mhellstr - normally the developers of the interface add the examples to the folder, but because we were doing a lot of work there I thought I could add to my todo list to add it. I didn't get to it yet because it got buried in other i-PI related tasks. so, if you can do it, it is guaranteed to appear soon! if you can't, I can still get there in the future. What held me back is that I could not just copy/paste the example because it also depends on ASE and it would take a few more steps to include it in our tests. @ceriottm and @litman90 - do you think it would be acceptable in this case to just ignore the folder but leave it in the main code examples folders? If so, it would just be a matter of copy/paste

**Comment by litman90** [comment]
Thanks for your contribution @mhellstr 
I agree with @mahrossi.

Please @mhellstr could you add a simple example using AMS to  i-pi/examples/clients/AMS with a nice README.md? 
If the workflow is failing just tag me in the PR and can help you out/fix it.

**Comment by mhellstr** [comment]
I'll put it on my todo list but may take a while. (There's no immediate rush from my side, I was just responding to Michele's comment.)

**Comment by litman90** [comment]
Hi @mhellstr, we are preparing the v3.0 release and writing the corresponding paper. It would be great to mention the interface to AMS.   Do you think you can add an example using AMS to i-pi/examples/clients/AMS with a nice README.md in the next weeks? Probaly it is mainly  just copying the example here (https://www.scm.com/doc/plams/examples/i-PI-AMS.html). I would do it myself but but I don't have access to AMS to test if the example works.

**Comment by litman90** [comment]
See PR #297
