### ISSUE TITLE
NVE simulations with `fixcom` use negative temperature when computing kinetic energy

### ISSUE THREAD

**Issue by svandenhaute** [i-pi/i-pi#337]
When simulating in the NVE ensemble, in combination with the `fixcom` tag, the calculation of the kinetic energy still relies on `ensemble.temp`:
https://github.com/i-pi/i-pi/blob/68fb0b30c0ee4e4c5187aa64f96087e57ec7f227/ipi/engine/properties.py#L1094

Since this is set to `-1.0` when no temperature is specified (as one would expect), the square root evaluates to `nan`.

Potentially related to #336

**Comment by mahrossi** [comment]
I think that instead we should enforce that a temperature is always set in case of nbeads > 1, even in the case of NVE - this is because if you run PIMD with NVE but no temperature, the spring constants make no sense. 

THEN for nbeads = 1 we really need to be more careful, because this hack to evaluate the temperature is not good anyways. Thanks for reporting.

**Comment by ceriottm** [comment]
This should be fixed by #368
